apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: lab3
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
