apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql_pvc
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"