apiVersion: apps/v1  
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1    
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 374997061608.dkr.ecr.us-east-1.amazonaws.com/my_sql:v0.3
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        volumeMounts:
        - name: mysql-host
          mountPath: /var/lib/mysql          
        ports:
        - containerPort: 3306
      volumes:
       - name: mysql-host
         persistentVolumeClaim:
           claimName: mysql-host  
