apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-host
spec:
  capacity:
    storage: 4Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: localstorage
  hostPath:
    path: /tmp/data