apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-host
  namespace: lab3
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: localstorage
  resources:
    requests:
      storage: 1Gi